FROM docker.io/library/r-base:latest
LABEL maintainer="abanderb@redhat.com"
LABEL description="R runtime image for dashboard demo."
LABEL version="2.0"
USER root
RUN apt-get update && apt-get install -y libssl-dev libgdal-dev libgeos-dev libproj-dev libtbb-dev libnetcdf-dev libtool automake
RUN R -q -e 'install.packages(c("shiny","httr2","shinychat", "ellmer", "bslib"), repos = "https://cran.rstudio.com/")'
RUN mkdir /application /.cache /application/www
RUN chmod 777 /.cache /application/www
COPY app.r /application
WORKDIR /application
USER 1001
EXPOSE 8080
ENTRYPOINT R -s -e 'source("/application/app.r")'